config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :yfcases do
	resources :subsigntrueas, :controller => "yfcase_subsigntruea"
	resources :subsigntruebs, :controller => "yfcase_subsigntrueb"
	resources :subsigntruecs, :controller => "yfcase_subsigntruec"
  	resources :objectbuilds do 
		resources :plusrateas, :controller => "objectbuild_plusrateas"
		resources :plusratebs, :controller => "objectbuild_plusratebs"
		member do
			get :editplusratea, :controller => "yfcase_objectbuilds"
			get :editplusrateb, :controller => "yfcase_objectbuilds"
			patch :updateplusratea , :controller => "yfcase_objectbuilds"
			patch :updateplusrateb , :controller => "yfcase_objectbuilds"
			delete :deleteplusratea , :controller => "yfcase_objectbuilds" #刪除加成人員A及加成A
			delete :deleteplusrateb , :controller => "yfcase_objectbuilds" #刪除加成人員B及加成B
		end
	end
	member do
		get :yfratingscale #YF評量表
		get :deedtax #契稅申請書
		get :realestateregistration #不動產登記
		get :complaint #訴訟狀
		delete :delete_subsigntruea #刪除副署人員1
		delete :delete_subsigntrueb #刪除副署人員2
		delete :delete_subsigntruec #刪除副署人員3
		
	end
  end
  root to: "yfcases#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/yfcase_subsigntrueb_controller.rb
class YfcaseSubsigntruebController < ApplicationController
	before_action :set_yfcase
	def index
	
	end

	def new
		@signtrueb = @yfcase.subsigntruebs.new
	end

	def create
		@signtrueb = @yfcase.subsigntruebs.new(signtrueb_params)
		if @signtrueb.save
			redirect_to yfcase_path(@yfcase)
		else
			render :action => "new"
		end
	end

	protected
	def set_yfcase
		@yfcase=Yfcase.find(params[:yfcase_id])
	end

	def signtrueb_params
		params.require(:subsigntrueb).permit(:signtrueb,:signtrueb_first_name,:signtrueb_last_name,:signtrueb_date)
	end
end

app/helpers/yfcase_subsigntrueb_helper.rb
module YfcaseSubsigntruebHelper
end

app/views/yfcase_subsigntrueb/new.html.erb
<h2>New</h2>
<%= current_user.first_name %><%= current_user.last_name %>
<%= form_for @signtrueb , :url => yfcase_subsigntruebs_path( @yfcase ) do |f| %>
<div class="form-group">
    <%= f.hidden_field :signtrueb, :value => "#{current_user.first_name}#{current_user.last_name}" %>
    <%= f.hidden_field :signtrueb_first_name, :value => "#{current_user.first_name}" %>
    <%= f.hidden_field :signtrueb_last_name, :value => "#{current_user.last_name}" %>
    <%= f.hidden_field :signtrueb_date, :value => "#{Time.now.strftime('%Y-%m-%d')}" %>
</div>

<div class="form-group">
    <%= f.submit "同意", :class => "btn btn-primary" %>
</div>
<% end %>
<%= link_to "返回", yfcase_path(@yfcase) %>