config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :yfcases do
	resources :subsigntrueas, :controller => "yfcase_subsigntruea"
	resources :subsigntruebs, :controller => "yfcase_subsigntrueb"
	resources :subsigntruecs, :controller => "yfcase_subsigntruec"
  	resources :objectbuilds do 
		resources :plusrateas, :controller => "objectbuild_plusrateas"
		resources :plusratebs, :controller => "objectbuild_plusratebs"
		member do
			get :editplusratea, :controller => "yfcase_objectbuilds"
			get :editplusrateb, :controller => "yfcase_objectbuilds"
			patch :updateplusratea , :controller => "yfcase_objectbuilds"
			patch :updateplusrateb , :controller => "yfcase_objectbuilds"
			delete :deleteplusratea , :controller => "yfcase_objectbuilds" #刪除加成人員A及加成A
			delete :deleteplusrateb , :controller => "yfcase_objectbuilds" #刪除加成人員B及加成B
		end
	end
	member do
		get :yfratingscale #YF評量表
		get :deedtax #契稅申請書
		get :realestateregistration #不動產登記
		get :complaint #訴訟狀
		delete :delete_subsigntruea #刪除副署人員1
		delete :delete_subsigntrueb #刪除副署人員2
		delete :delete_subsigntruec #刪除副署人員3
		
	end
  end
  root to: "yfcases#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/yfcase_objectbuilds_controller.rb
class YfcaseObjectbuildsController < ApplicationController
	before_action :set_plus
	def editplusratea
		@plusa = @yfcase.objectbuilds.find(params[:id])
	end

	def updateplusratea
		@plusa = @yfcase.objectbuilds.find(params[:id])
		if @plusa.update(plusa_params)
			redirect_to yfcase_path( @yfcase )
		else
			render :action => "editplus"
		end
	end

	def deleteplusratea
		@plusa = @yfcase.objectbuilds.find(params[:id])
		@plusa.update(surveyora: nil, plusa: nil)
		redirect_to yfcase_path( @yfcase )
	end

	def editplusrateb
		@plusb = @yfcase.objectbuilds.find(params[:id])
	end

	def updateplusrateb
		@plusb = @yfcase.objectbuilds.find(params[:id])
		if @plusb.update(plusa_params)
			redirect_to yfcase_path( @yfcase )
		else
			render :action => "editplusrateb"
		end
	end
	
	def deleteplusrateb
		@plusb = @yfcase.objectbuilds.find(params[:id])
		@plusb.update(surveyorb: nil, plusb: nil)
		redirect_to yfcase_path( @yfcase )
	end
	
	protected
	def set_plus
		@yfcase=Yfcase.find(params[:yfcase_id])
	end

	def plusa_params
		params.require(:objectbuild).permit(:plusa,:plusb,:surveyora,:surveyorb)
	end
end

app/helpers/yfcase_objectbuilds_helper.rb
module YfcaseObjectbuildsHelper
end

app/views/yfcase_objectbuilds/editplusratea.html.erb
<h1>加成A</h1>

<%= form_for @plusa , :url => updateplusratea_yfcase_objectbuild_path( @yfcase,@plusa), method: :patch do |f| %>
<div class="form-group">
    <%= f.label :plusa %>
    <%= f.number_field :plusa, in: 0..10, :step => 0.01, :required => true , :class => "form-control" %>
    <%= f.hidden_field :surveyora, :value => "#{current_user.first_name}#{current_user.last_name}" %>
</div>

<div class="form-group">
    <%= f.submit :class => "btn btn-primary" %>
</div>
<% end %>
<%= link_to "back", yfcase_path(@yfcase) %>

app/views/yfcase_objectbuilds/editplusrateb.html.erb
<h1>加成B</h1>

<%= form_for @plusb , :url => updateplusrateb_yfcase_objectbuild_path( @yfcase,@plusb), method: :patch do |f| %>
<div class="form-group">
    <%= f.label :plusb %>
    <%= f.number_field :plusb, in: 0..10, :step => 0.01, :required => true , :class => "form-control" %>
    <%= f.hidden_field :surveyorb, :value => "#{current_user.first_name}#{current_user.last_name}" %>
</div>

<div class="form-group">
    <%= f.submit :class => "btn btn-primary" %>
</div>
<% end %>
<%= link_to "back", yfcase_path(@yfcase) %>