config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :yfcases do
	resources :subsigntrueas, :controller => "yfcase_subsigntruea"
	resources :subsigntruebs, :controller => "yfcase_subsigntrueb"
	resources :subsigntruecs, :controller => "yfcase_subsigntruec"
  	resources :objectbuilds do 
		resources :plusrateas, :controller => "objectbuild_plusrateas"
		resources :plusratebs, :controller => "objectbuild_plusratebs"
		member do
			get :editplusratea, :controller => "yfcase_objectbuilds"
			get :editplusrateb, :controller => "yfcase_objectbuilds"
			patch :updateplusratea , :controller => "yfcase_objectbuilds"
			patch :updateplusrateb , :controller => "yfcase_objectbuilds"
			delete :deleteplusratea , :controller => "yfcase_objectbuilds" #刪除加成人員A及加成A
			delete :deleteplusrateb , :controller => "yfcase_objectbuilds" #刪除加成人員B及加成B
		end
	end
	member do
		get :yfratingscale #YF評量表
		get :deedtax #契稅申請書
		get :realestateregistration #不動產登記
		get :complaint #訴訟狀
		delete :delete_subsigntruea #刪除副署人員1
		delete :delete_subsigntrueb #刪除副署人員2
		delete :delete_subsigntruec #刪除副署人員3
		
	end
  end
  root to: "yfcases#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Yangfurails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- 下列三行要在後面才執行，不然地址無法連動 -->
    <%= stylesheet_link_tag "/css/jquery-ui.min.css" %>
    <script src="/js/jquery-3.4.1.max.js"></script>
    <script src="/js/jquery-ui.min.js"></script>
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">
            <%= link_to 'YF', root_path %>
        </h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <% if user_signed_in? %>
                <a class="p-2 text-dark">
                    (<%= current_user.first_name %><%= current_user.last_name %>)
                </a>
              <%= link_to "建立YF評量表", new_yfcase_path, class: "btn btn-outline-info p-2" %>
              <%= link_to "登出", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger p-2" %>
            <% else %>
              <%= link_to "註冊", new_user_registration_path, class: "btn btn-outline-success p-2" %>
              <%= link_to "登入", new_user_session_path, class: "btn btn-outline-primary p-2" %>
            <% end %>
        </nav>
    </div>
    <div class="container center" style="width:1000px;">
        <% flash.each do |name, msg| %>
          <% content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>
        <%= yield %>
    </div>

</body>

</html>